USE [master]
GO

/****** Object:  Database [VoyageCare]    Script Date: 04/05/2022 16:42:47 ******/
CREATE DATABASE [VoyageCare]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VoyageCare', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VoyageCare.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VoyageCare_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\VoyageCare_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VoyageCare].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [VoyageCare] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [VoyageCare] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [VoyageCare] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [VoyageCare] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [VoyageCare] SET ARITHABORT OFF 
GO

ALTER DATABASE [VoyageCare] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [VoyageCare] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [VoyageCare] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [VoyageCare] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [VoyageCare] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [VoyageCare] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [VoyageCare] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [VoyageCare] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [VoyageCare] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [VoyageCare] SET  DISABLE_BROKER 
GO

ALTER DATABASE [VoyageCare] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [VoyageCare] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [VoyageCare] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [VoyageCare] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [VoyageCare] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [VoyageCare] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [VoyageCare] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [VoyageCare] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [VoyageCare] SET  MULTI_USER 
GO

ALTER DATABASE [VoyageCare] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [VoyageCare] SET DB_CHAINING OFF 
GO

ALTER DATABASE [VoyageCare] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [VoyageCare] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [VoyageCare] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [VoyageCare] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [VoyageCare] SET QUERY_STORE = OFF
GO

ALTER DATABASE [VoyageCare] SET  READ_WRITE 
GO


